title: SIGTACS
logo:
description: Special Interest Group on Theoretical Aspects of Computer Science, was born out of an effort to bring together people interested in areas of Theoretical Computer Science. It is a platform for students and faculty members to come together and share their excitement in the area. The group aims at organizing problem solving sessions, seminars and guest lectures. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

permalink: /:year-:month-:day-:title/
paginate: 10
paginate_path: "/talks/page:num/"
url: "https://sigtacs.github.io"
baseurl: ""

# List of links in the navigation bar
navbar-links:
  - title: About
    url:

  - title: Talks
    url: 

  - title: Lecture Series
    url:

plugins:
  - jekyll-paginate