title: SIGTACS
logo:
description: Special Interest Group on Theoretical Aspects of Computer Science, was born out of an effort to bring together people interested in areas of Theoretical Computer Science.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
