name: Jekyll Deploy

on: [push]

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build & Deploy to GitHub Pages
        run : |
          # cleanup "_site"
          rm -rf _site
          mkdir _site
          
          # clone remote repo to "_site"
          git clone https://github.com/SIGTACS/SIGTACS.github.io.git --branch gh-pages _site
          
          # build with Jekyll into "_site"
          bundle exec jekyll build

          # push
          cd _site
          git config user.email "prateek.dwv21@gmail.com"
          git config user.name "Prateek Dwivedi"
          git add --all
          git commit -a -m "Action Build"
          git push --force origin gh-pages
